version: '3.8'

services:
  esp32-dashboard:
    build: .
    container_name: esp32-dashboard
    restart: unless-stopped
    expose:
      - 8081 
    environment:
      - TZ=Europe/Paris
    env_file:
      - .env # Charge les variables d'environnement
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    networks:
      - services_net

networks:
  services_net:
    external: true